In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./dataset/서울특별시_부동산_실거래가_정보_2017년.csv',encoding='cp949')

C:\Users\User\AppData\Local\Temp\ipykernel_5628\1880749539.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./dataset/서울특별시_부동산_실거래가_정보_2017년.csv',encoding='cp949')

In [5]:
df.head()

,실거래가아이디,지번코드,시군구코드,자치구명,법정동코드,법정동명,신고년도,업무구분코드,업무구분,물건번호,대지권면적,건물면적,관리구분코드,층정보,건물주용도코드,건물주용도,물건금액,건축년도,건물명
0,11170-2017-4-0014572-1,1117011900100130000,11170,용산구,1117011900,효창동,2017,4,신고,1,0.0,84.91,1,4.0,2001,아파트,881400000,0.0,용산 롯데캐슬 센터포레
1,11230-2017-4-0012888-1,1123010500100250000,11230,동대문구,1123010500,답십리동,2017,4,신고,1,0.0,59.91,1,11.0,2001,아파트,597000000,0.0,답십리파크자이
2,11230-2017-4-0014413-1,1123010500100250000,11230,동대문구,1123010500,답십리동,2017,4,신고,1,0.0,49.54,1,15.0,2001,아파트,480300000,0.0,답십리파크자이
3,11545-2017-4-0003477-1,1154510200104410014,11545,금천구,1154510200,독산동,2017,4,신고,1,0.0,84.41,1,36.0,2001,아파트,548200000,0.0,롯데캐슬 골드파크 ３차
4,11545-2017-4-0008616-1,1154510200104410014,11545,금천구,1154510200,독산동,2017,4,신고,1,0.0,59.97,1,15.0,2001,아파트,500300000,0.0,롯데캐슬 골드파크 ３차

In [6]:
col = df.loc[ : ,['자치구명', '법정동명', '건물면적', '층정보', '건물주용도',
                  '건물명', '물건금액']].copy()
col.head()

   자치구명  법정동명   건물면적   층정보 건물주용도           건물명       물건금액
0   용산구   효창동  84.91   4.0   아파트  용산 롯데캐슬 센터포레  881400000
1  동대문구  답십리동  59.91  11.0   아파트       답십리파크자이  597000000
2  동대문구  답십리동  49.54  15.0   아파트       답십리파크자이  480300000
3   금천구   독산동  84.41  36.0   아파트  롯데캐슬　골드파크　３차  548200000
4   금천구   독산동  59.97  15.0   아파트  롯데캐슬　골드파크　３차  500300000

In [ ]:
col.info()

In [11]:
mask_1 = (col.건물주용도 =='아파트')
col_mask = col.loc[mask_1, :]
col_mask.head()

   자치구명  법정동명   건물면적   층정보 건물주용도           건물명       물건금액
0   용산구   효창동  84.91   4.0   아파트  용산 롯데캐슬 센터포레  881400000
1  동대문구  답십리동  59.91  11.0   아파트       답십리파크자이  597000000
2  동대문구  답십리동  49.54  15.0   아파트       답십리파크자이  480300000
3   금천구   독산동  84.41  36.0   아파트  롯데캐슬　골드파크　３차  548200000
4   금천구   독산동  59.97  15.0   아파트  롯데캐슬　골드파크　３차  500300000

In [12]:
apt_col = col_mask.copy()
apt17 = apt_col.rename(columns={'법정동명':'동이름', '건물주용도':'건물용도',
                                '건물면적':'건물면적(㎡)', '물건금액':'거래가격(만원)'})
apt17.head()

   자치구명   동이름  건물면적(㎡)   층정보 건물용도           건물명   거래가격(만원)
0   용산구   효창동    84.91   4.0  아파트  용산 롯데캐슬 센터포레  881400000
1  동대문구  답십리동    59.91  11.0  아파트       답십리파크자이  597000000
2  동대문구  답십리동    49.54  15.0  아파트       답십리파크자이  480300000
3   금천구   독산동    84.41  36.0  아파트  롯데캐슬　골드파크　３차  548200000
4   금천구   독산동    59.97  15.0  아파트  롯데캐슬　골드파크　３차  500300000

In [13]:
apt17.set_index(['자치구명','동이름'],inplace=True)
apt17

            건물면적(㎡)   층정보 건물용도           건물명   거래가격(만원)
자치구명 동이름
용산구  효창동      84.91   4.0  아파트  용산 롯데캐슬 센터포레  881400000
동대문구 답십리동     59.91  11.0  아파트       답십리파크자이  597000000
     답십리동     49.54  15.0  아파트       답십리파크자이  480300000
금천구  독산동      84.41  36.0  아파트  롯데캐슬　골드파크　３차  548200000
     독산동      59.97  15.0  아파트  롯데캐슬　골드파크　３차  500300000
...             ...   ...  ...           ...        ...
영등포구 양평동3가    84.92   7.0  아파트        우림루미아트  550000000
     문래동5가    65.46   9.0  아파트       문래 두산위브  390000000
     당산동5가   115.78  15.0  아파트         삼성래미안  940000000
     도림동      84.76  28.0  아파트       영등포아트자이  675000000
     여의도동     94.31   8.0  아파트            진주  960000000

[109491 rows x 5 columns]

In [14]:
건물면적_to_평수 = 1 * 0.3025 #평수 작업 줄
apt17['평수'] = apt17['건물면적(㎡)'] * 건물면적_to_평수 #평수 column 으로 생성
apt17['평수'] = apt17['평수'].round(0)
apt17

            건물면적(㎡)   층정보 건물용도           건물명   거래가격(만원)    평수
자치구명 동이름
용산구  효창동      84.91   4.0  아파트  용산 롯데캐슬 센터포레  881400000  26.0
동대문구 답십리동     59.91  11.0  아파트       답십리파크자이  597000000  18.0
     답십리동     49.54  15.0  아파트       답십리파크자이  480300000  15.0
금천구  독산동      84.41  36.0  아파트  롯데캐슬　골드파크　３차  548200000  26.0
     독산동      59.97  15.0  아파트  롯데캐슬　골드파크　３차  500300000  18.0
...             ...   ...  ...           ...        ...   ...
영등포구 양평동3가    84.92   7.0  아파트        우림루미아트  550000000  26.0
     문래동5가    65.46   9.0  아파트       문래 두산위브  390000000  20.0
     당산동5가   115.78  15.0  아파트         삼성래미안  940000000  35.0
     도림동      84.76  28.0  아파트       영등포아트자이  675000000  26.0
     여의도동     94.31   8.0  아파트            진주  960000000  29.0

[109491 rows x 6 columns]

In [17]:
apt17_sorted = apt17[['건물명', '건물용도', '층정보', '거래가격(만원)', '평수', '건물면적(㎡)']]
apt17_sorted.head()

                    건물명 건물용도   층정보   거래가격(만원)    평수  건물면적(㎡)
자치구명 동이름
용산구  효창동   용산 롯데캐슬 센터포레  아파트   4.0  881400000  26.0    84.91
동대문구 답십리동       답십리파크자이  아파트  11.0  597000000  18.0    59.91
     답십리동       답십리파크자이  아파트  15.0  480300000  15.0    49.54
금천구  독산동   롯데캐슬　골드파크　３차  아파트  36.0  548200000  26.0    84.41
     독산동   롯데캐슬　골드파크　３차  아파트  15.0  500300000  18.0    59.97

In [18]:
apt17_sorted_1 = apt17_sorted.sort_values(by = '거래가격(만원)')
apt17_sorted_1

                     건물명 건물용도  층정보    거래가격(만원)    평수  건물면적(㎡)
자치구명 동이름
강서구  화곡동  SR vill(925-3)  아파트  7.0    61000000   4.0    14.01
     화곡동  SR vill(925-3)  아파트  7.0    63000000   4.0    14.22
     화곡동  SR vill(925-3)  아파트  8.0    63000000   4.0    14.22
     화곡동  SR vill(925-3)  아파트  8.0    63000000   4.0    14.22
     화곡동  SR vill(925-3)  아파트  7.0    63000000   4.0    14.22
...                  ...  ...  ...         ...   ...      ...
용산구  한남동            한남더힐  아파트  3.0  6300000000  73.0   240.31
     한남동            한남더힐  아파트  3.0  6500000000  73.0   240.23
     한남동            한남더힐  아파트  1.0  7270000000  74.0   243.64
     한남동            한남더힐  아파트  3.0  7800000000  74.0   244.78
     한남동            한남더힐  아파트  3.0  8200000000  74.0   244.75

[109491 rows x 6 columns]

In [23]:
apt17_sorted_1.to_csv('APT2017.csv')